# Generated by Django 4.2.2 on 2023-06-17 20:58

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('user_role', models.CharField(choices=[('STUDENT', 'Student'), ('MENTOR', 'Mentor'), ('ADMIN', 'Admin')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('user', django.db.models.manager.Manager()),
            ],
        ),
    ]
