# Generated by Django 4.2.2 on 2023-06-17 21:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_account.user',),
            managers=[
                ('user', django.db.models.manager.Manager()),
            ],
        ),
    ]
