# Generated by Django 4.2.2 on 2023-06-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
