# Generated by Django 4.2.3 on 2023-07-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_catogaries_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_profile',
            field=models.ImageField(blank=True, upload_to='Media/author'),
        ),
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='Media/featured_img'),
        ),
    ]
