# Generated by Django 4.2.2 on 2023-07-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_author_author_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='featured_video',
        ),
        migrations.AddField(
            model_name='course',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
