# Generated by Django 4.2.2 on 2023-07-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_author_id_alter_catogaries_id_alter_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catogaries',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.RemoveField(
            model_name='course',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
