# Generated by Django 4.2.2 on 2023-07-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_catogaries_icon_remove_course_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catogaries',
            name='category_image',
            field=models.ImageField(blank=True, upload_to='course/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='featured_img/'),
        ),
    ]
