# Generated by Django 4.2.3 on 2023-07-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_catogaries_id_alter_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
