# Generated by Django 4.2.3 on 2023-07-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_course_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='zip_folders/'),
        ),
    ]
