# Generated by Django 4.2.2 on 2023-07-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_courseview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='zip_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='zip_folders/'),
        ),
    ]
