# Generated by Django 4.1.7 on 2023-03-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
                ('Role', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
                # ('InternshipDuration', models.IntegerField(serialize=False)),
                ('Intake', models.CharField(max_length=200)),
            ],
        ),
    ]
